---
# $ ansible-playbook -i devops/inventories/dynamic \
#   devops/run_aws_lambda_with_s3_tutorial.yml \
#   --private-key=./private.pem -u ec2-user --extra-vars="overrides_filename=aws_with_amazon_s3_tutorial_vars.y

# localhost
- name: setup ansible-lambda modules
  hosts: localhost
  gather_facts: no
  roles:
    - ansible-lambda

- include: "{{ playbook_dir }}/iam_create_user.yml"

- name: create ec2 instance
  hosts: localhost
  gather_facts: yes
  roles:
    - create_box_ec2

- include: "{{ playbook_dir }}/create_s3_buckets.yml"

- name: upload test image
  hosts: localhost
  gather_facts: no
  tasks:
    - name: upload HappyFace.jpg
      s3:
        bucket: "{{ s3_bucket_names[0].name }}"
        region: "{{ region }}"
        mode: put
        permission: "public-read-write"
        object: HappyFace.jpg
        src: "{{ playbook_dir }}/files/lambda_tutorial/images/HappyFace.jpg"
      register: s3_put_output

# remote ec2
- include: "{{ playbook_dir }}/build_and_bundle_on_ec2.yml"

# localhost
- include: "{{ playbook_dir }}/upload_bundle_to_s3.yml"

- include: "{{ playbook_dir }}/create_aws_lambda_function.yml"