---

- name: create s3 bucket with policy
  s3:
    bucket: "{{ item.name }}"
    region: "{{ region }}"
    mode: create
    permission: "public-read-write"
  with_items: s3_bucket_names
  register: s3_output

- debug: msg="{{ s3_output }}"
