---
- include_vars: vars/overrides_and_extras.yml

- name: create s3 bucket without policy
  s3:
    bucket: "{{ item.name }}"
    region: "{{ region }}"
    mode: create
    permission: "public-read-write"
  with_items: s3_bucket_names
  register: s3_output
#- debug: msg="{{ s3_output }}"

- name: create s3 bucket for code
  s3:
    bucket: "{{ s3_code_bucket_name }}"
    region: "{{ region }}"
    mode: create
    permission: "public-read-write"
  register: s3_output
#- debug: msg="{{ s3_output }}"


- name: upload HappyFace.jpg
  s3:
    bucket: "{{ s3_bucket_names[0].name }}"
    region: "{{ region }}"
    mode: put
    permission: "public-read-write"
    object: HappyFace.jpg
    src: "{{ role_path }}/files/HappyFace.jpg"
  register: s3_put_output
#- debug: msg="{{ s3_put_output }}"
