---
- debug: msg="Matched Groups:{{groups}}"

- name: install python-dev headers
  apt:
    name: python-dev
    state: present

- name: install psycopg2
  apt:
    name: python-psycopg2
    state: present

- name: install postgresql
  apt:
    name: postgresql-9.3
    state: present

- name: install postgresql-common
  apt:
    name: postgresql-common
    state: present

- name: install postgresql-contrib
  apt:
    name: postgresql-contrib-9.3
    state: present

- name: add pg_hba.conf
  template:
    src: ../templates/pg_hba.conf.j2
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify: restart postgresql
